# Generated by Django 4.1.7 on 2023-02-21 17:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asiangemological', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 2, 21, 17, 54, 49, 946667, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='dimension',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='identified_as',
            field=models.CharField(default=datetime.datetime(2023, 2, 21, 17, 55, 9, 934272, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='item_described',
            field=models.CharField(default=datetime.datetime(2023, 2, 21, 17, 54, 15, 138817), max_length=30),
        ),
        migrations.AddField(
            model_name='stone',
            name='shape',
            field=models.CharField(default=datetime.datetime(2023, 2, 21, 17, 55, 16, 458294, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='weight',
            field=models.CharField(default=datetime.datetime(2023, 2, 21, 17, 55, 23, 54624, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
