# Generated by Django 4.1.7 on 2023-02-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiangemological', '0002_stone_color_stone_date_stone_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='item_described',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stone',
            name='verification_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
