# Generated by Django 4.1.7 on 2023-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiangemological', '0005_stone_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='date',
            field=models.DateField(),
        ),
    ]
