# Generated by Django 4.1.7 on 2023-03-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiangemological', '0006_alter_stone_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='artificial_faces',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='clarity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='indication_of_tampering',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='metal_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='natural_faces',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='other',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='refractive_index',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='specific_gravity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stone',
            name='transparency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stone',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stone',
            name='identified_as',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stone',
            name='item_described',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stone',
            name='shape',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stone',
            name='verification_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
